name: deploy-AWS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
      - name: copy files to the deploy server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: "ubuntu"
          key: ${{ secrets.AWS_EC2_KEY }}
          source: "composer.json composer.lock index.php makefile manifest.json bin/ cfg/ css/ i18n/ img/ js/ lib/ tpl/ tst/"
          target: '/home/ubuntu/PrivateBin'

      - name: run composer install and run php server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: "ubuntu"
          key: ${{ secrets.AWS_EC2_KEY }}
          script: deploy.sh          
