name: Code Coverage Summary
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: php-actions/composer@v6
      
      - uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: phpunit.xml
          badge: true
          format: markdown
