name: Code Coverage Summary
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: phpunit.xml
          badge: true
          format: markdown
