name: phpcs
on: 
  push:
    branches:
      - "master"
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: lib
          standard: PSR1
  
      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 7.3
          path: lib
          output: text
          ruleset: cleancode
          reportfile: phpmd.md
    
      - name : Markdown
        run: cat phpmd.md >> $GITHUB_STEP_SUMMARY
